
train:
  freeze_body: false
  freeze_head: false
  pretrained_model:
  resume_from:
  init_type: xavier
  work_dir: checkpoint
  num_epochs: 200
  batch_size: 64
  start_epoch: 0
  use_tensorboard: false
  val_epochs: 1
  open_tensorboard: true

#  注释性质
data:
  input_size:
    - 224
    - 224
  type: rgb
  mean: 0
  std: 255

device:
  cuda_index:
    - '0'
  use_cuda: true


model:
  type: Net2
  num_classes: 2

scheduler:
  type: torch.optim.lr_scheduler.StepLR
  step_size: 7
  gamma: 0.1

optimizer:
  type: torch.optim.SGD
  lr: 0.001
  momentum: 0.9

loss:
  type: nn.CrossEntropyLoss

transform:
  - type: Resize
    size: 224
  - type: ColorJitter
    saturation: 0.5
    hue: 0.1
#  - type: RandomCrop
#    size: 49
  - type: ToTensor
target_transform: ~
val_transform:
  - type: Resize
    size: 224
val_target_transform: ~

train_datasets:
  - type: ImageFolder
    root: /home/cmf/datasets/helmet/helmet_all/train_val/train
val_datasets:
  - type: ImageFolder
    root: /home/cmf/datasets/helmet/helmet_all/train_val/val
dataloader:
  batch_size: 64
  num_workers: 4
  shuffle: true