model:
  type: Net2
  num_classes: 2

scheduler:
  type: MultiStep

device:
  cuda_index:
    - '0'
  use_cuda: true

optimizer:
  type: nn.SGD
  lr: 1e-2
  momentum: 0.9

loss:
  type: CrossEntropyLoss

train:
  freeze_base: false
  freeze_head: false
  pretrained_model: ~
  resume_from: ~
  init_type: xavier
  work_dir: checkpoint
  num_epochs: 200
  batch_size: 24
  start_epochs: 0

data:
  input_size:
    - 224
    - 224
  train_datasets:
    - null
  train_datasets_type:
    - ImageFolder
  validation_datasets:
    - null
  validation_datasets_type:
    - ImageFolder
  num_worker: 4
  seed: ~

transform: ~
target_transform: ~
train_datasets:
  - type: ImageFolder
validation_datasets:
  - type: ImageFolder
dataloader:
  batch_size: 24
  num_worker: 4
  shuffle: true