model:
  type: 'resnet18'
train_cfg: ''
data:
  batch_size: 32
  num_workers: 4
  train:
    img_scale:
      - 224
      - 224
  val:
    img_scale:
      - 224
      - 224
  test:
    img_scale:
      - 224
      - 224

img_norm_cfg:
  mean:
    - 0.485
    - 0.456
    - 0.406
  std:
    - 0.229
    - 0.224
    - 0.225
total_epochs: 12
work_dir: 'checkpoint'